//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/Testing/TugControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Testing/TugControls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @TugControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @TugControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""TugControls"",
    ""maps"": [
        {
            ""name"": ""Tug"",
            ""id"": ""e9246273-2695-4392-acd1-ade062553059"",
            ""actions"": [
                {
                    ""name"": ""LeftEngineDirection"",
                    ""type"": ""Value"",
                    ""id"": ""600884c6-53b8-4634-8876-8d2832e1f29b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightEngineDirection"",
                    ""type"": ""Value"",
                    ""id"": ""fd4094d3-837f-4a51-9b50-36b66d480dfd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftEngineThrust"",
                    ""type"": ""Value"",
                    ""id"": ""065cfcc7-43e6-4093-aabf-6434e99ef498"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightEngineThrust"",
                    ""type"": ""Value"",
                    ""id"": ""7f3eada0-b583-4b94-bff5-2296cbb2c0d2"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""EmergencyStop"",
                    ""type"": ""Button"",
                    ""id"": ""b115fe5e-659f-480d-8b41-503cddb6ad08"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""99c685f4-656d-464e-bc15-ecbd8b557f53"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftEngineDirection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94ae0c55-2451-43d1-89bd-13afd75e00ea"",
                    ""path"": ""<Joystick>/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftEngineDirection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13ff046d-6429-42e8-9a05-228db4c5fa05"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightEngineDirection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f6bd615-b74a-4e63-aa8f-4be8229f5092"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftEngineThrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b70d3a3-9647-440e-ab37-2f786b072592"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightEngineThrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2bdbbdfd-5a18-4f7a-a60f-f57d48961bf0"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EmergencyStop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Tug
        m_Tug = asset.FindActionMap("Tug", throwIfNotFound: true);
        m_Tug_LeftEngineDirection = m_Tug.FindAction("LeftEngineDirection", throwIfNotFound: true);
        m_Tug_RightEngineDirection = m_Tug.FindAction("RightEngineDirection", throwIfNotFound: true);
        m_Tug_LeftEngineThrust = m_Tug.FindAction("LeftEngineThrust", throwIfNotFound: true);
        m_Tug_RightEngineThrust = m_Tug.FindAction("RightEngineThrust", throwIfNotFound: true);
        m_Tug_EmergencyStop = m_Tug.FindAction("EmergencyStop", throwIfNotFound: true);
    }

    ~@TugControls()
    {
        UnityEngine.Debug.Assert(!m_Tug.enabled, "This will cause a leak and performance issues, TugControls.Tug.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Tug
    private readonly InputActionMap m_Tug;
    private List<ITugActions> m_TugActionsCallbackInterfaces = new List<ITugActions>();
    private readonly InputAction m_Tug_LeftEngineDirection;
    private readonly InputAction m_Tug_RightEngineDirection;
    private readonly InputAction m_Tug_LeftEngineThrust;
    private readonly InputAction m_Tug_RightEngineThrust;
    private readonly InputAction m_Tug_EmergencyStop;
    /// <summary>
    /// Provides access to input actions defined in input action map "Tug".
    /// </summary>
    public struct TugActions
    {
        private @TugControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public TugActions(@TugControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Tug/LeftEngineDirection".
        /// </summary>
        public InputAction @LeftEngineDirection => m_Wrapper.m_Tug_LeftEngineDirection;
        /// <summary>
        /// Provides access to the underlying input action "Tug/RightEngineDirection".
        /// </summary>
        public InputAction @RightEngineDirection => m_Wrapper.m_Tug_RightEngineDirection;
        /// <summary>
        /// Provides access to the underlying input action "Tug/LeftEngineThrust".
        /// </summary>
        public InputAction @LeftEngineThrust => m_Wrapper.m_Tug_LeftEngineThrust;
        /// <summary>
        /// Provides access to the underlying input action "Tug/RightEngineThrust".
        /// </summary>
        public InputAction @RightEngineThrust => m_Wrapper.m_Tug_RightEngineThrust;
        /// <summary>
        /// Provides access to the underlying input action "Tug/EmergencyStop".
        /// </summary>
        public InputAction @EmergencyStop => m_Wrapper.m_Tug_EmergencyStop;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Tug; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="TugActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(TugActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="TugActions" />
        public void AddCallbacks(ITugActions instance)
        {
            if (instance == null || m_Wrapper.m_TugActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TugActionsCallbackInterfaces.Add(instance);
            @LeftEngineDirection.started += instance.OnLeftEngineDirection;
            @LeftEngineDirection.performed += instance.OnLeftEngineDirection;
            @LeftEngineDirection.canceled += instance.OnLeftEngineDirection;
            @RightEngineDirection.started += instance.OnRightEngineDirection;
            @RightEngineDirection.performed += instance.OnRightEngineDirection;
            @RightEngineDirection.canceled += instance.OnRightEngineDirection;
            @LeftEngineThrust.started += instance.OnLeftEngineThrust;
            @LeftEngineThrust.performed += instance.OnLeftEngineThrust;
            @LeftEngineThrust.canceled += instance.OnLeftEngineThrust;
            @RightEngineThrust.started += instance.OnRightEngineThrust;
            @RightEngineThrust.performed += instance.OnRightEngineThrust;
            @RightEngineThrust.canceled += instance.OnRightEngineThrust;
            @EmergencyStop.started += instance.OnEmergencyStop;
            @EmergencyStop.performed += instance.OnEmergencyStop;
            @EmergencyStop.canceled += instance.OnEmergencyStop;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="TugActions" />
        private void UnregisterCallbacks(ITugActions instance)
        {
            @LeftEngineDirection.started -= instance.OnLeftEngineDirection;
            @LeftEngineDirection.performed -= instance.OnLeftEngineDirection;
            @LeftEngineDirection.canceled -= instance.OnLeftEngineDirection;
            @RightEngineDirection.started -= instance.OnRightEngineDirection;
            @RightEngineDirection.performed -= instance.OnRightEngineDirection;
            @RightEngineDirection.canceled -= instance.OnRightEngineDirection;
            @LeftEngineThrust.started -= instance.OnLeftEngineThrust;
            @LeftEngineThrust.performed -= instance.OnLeftEngineThrust;
            @LeftEngineThrust.canceled -= instance.OnLeftEngineThrust;
            @RightEngineThrust.started -= instance.OnRightEngineThrust;
            @RightEngineThrust.performed -= instance.OnRightEngineThrust;
            @RightEngineThrust.canceled -= instance.OnRightEngineThrust;
            @EmergencyStop.started -= instance.OnEmergencyStop;
            @EmergencyStop.performed -= instance.OnEmergencyStop;
            @EmergencyStop.canceled -= instance.OnEmergencyStop;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="TugActions.UnregisterCallbacks(ITugActions)" />.
        /// </summary>
        /// <seealso cref="TugActions.UnregisterCallbacks(ITugActions)" />
        public void RemoveCallbacks(ITugActions instance)
        {
            if (m_Wrapper.m_TugActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="TugActions.AddCallbacks(ITugActions)" />
        /// <seealso cref="TugActions.RemoveCallbacks(ITugActions)" />
        /// <seealso cref="TugActions.UnregisterCallbacks(ITugActions)" />
        public void SetCallbacks(ITugActions instance)
        {
            foreach (var item in m_Wrapper.m_TugActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TugActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="TugActions" /> instance referencing this action map.
    /// </summary>
    public TugActions @Tug => new TugActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Tug" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="TugActions.AddCallbacks(ITugActions)" />
    /// <seealso cref="TugActions.RemoveCallbacks(ITugActions)" />
    public interface ITugActions
    {
        /// <summary>
        /// Method invoked when associated input action "LeftEngineDirection" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftEngineDirection(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightEngineDirection" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightEngineDirection(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftEngineThrust" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftEngineThrust(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightEngineThrust" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightEngineThrust(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "EmergencyStop" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnEmergencyStop(InputAction.CallbackContext context);
    }
}
